import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'tm': {
          'addDevice': '',
          'deleteTitle': 'Pozmak',
          'deleteSubtitle': 'Enjamy pozmak isleýärsiňizmi ? ',
          'sosHistory': 'SOS taryhy',
          'deviceList': 'Enjamlaryň sanawy',
          'select_language': 'Dil saýlaň',
          'selectMoreProducts': 'Bir ýa-da birnäçe önümi saýlamagyňyzy haýyş edýäris',
          'done': "Soňy",
          'cannotChangeOrderStatus': "Sargyt ýagdaýyny üýtgedip bilmersiňiz",
          "notHigherThanSumPrice": "Arzanladyş bahasy Jemi bahasyndan ýokary bolup bilmez",
          "createOrder": "Sargyt döretmek",
          'selectProducts': 'Harytlar saýlaň',
          'selectedProducts': 'Saýlanan harytlar',
          'dateOrder': 'Sargyt senesi:',
          'sales': "Sargytlar",
          'errorDontChangeData': "Siz hiç zat üýtgetmediňiz",
          'selectedImage': "Saýlanan surat",
          'totalProducts': 'Hemme harytlar',
          'stockInHand': 'Elimizdaki harytlar',
          'endOFProduct': 'Başga haryt ýok',
          'noProduct': "Harytlar tapylmady",
          'aboutUs': 'Biz barada',
          'add': 'Goş',
          'addAddress': 'Salgy goş',
          'addCart': 'Sebede goş',
          'added': 'Goşuldy',
          'addedSubtitle': 'Sebede haryt goşuldy ',
          'address': 'Öý salgyňyz',
          'agree': 'Tassyklamak',
          'alreadyExist': 'Ulanyjy maglumatlaryňyz bizde ýok. Hasaba al bölümden hasaba girmegiňizi haýýyş edýäris',
          'appColor': 'Programma reňki',
          'appColor1': 'Reňk saýlaň',
          'appColor2': 'Reňk 1',
          'appColor3': 'Reňk 2',
          'appColor4': 'Reňk 3',
          'appObtained': 'Hasap açmak isleseňiz, bu programmany alan adamyňyza ýüz tutmagyňyzy haýyş edýäris',
          'balance': 'Hasap',
          'banner': 'Reklama',
          'brand': 'Brand',
          'brandPP': 'Brand',
          'brands': 'Brendler',
          'call': 'Jaň et',
          'callNumber': 'Telefon Belgilerimiz',
          'cart': 'Sebet',
          'cartEmpty': 'Sebediňiz boş',
          'cartEmptySubtitle': 'Sebediňize hiç zat goşmadyňyz.',
          'cash': 'Nagt',
          'cashSubtitle': 'Sargydy alan wagtyňyz nagt görnüşde hasaplaşmak',
          'categoriesMini': 'Kategoriýalar',
          'category': 'Kategoriýa',
          'changesUpdated': 'Maglumatlar üýtgedildi',
          'chooseTheColor': 'Renk saýlaň : ',
          'chooseTheSize': 'Razmer :',
          'clientAddress': 'Ulanyjy salgysy',
          'clientNumber': 'Belgisi',
          'clientNumber': 'Telefon belgisi',
          'come': 'Geldi',
          'contactInformation': 'Habarlaşmak üçin : ',
          'container': 'Kontainer',
          'copySucces': 'Tassyklandy',
          'copySuccesSubtitle': 'Göçürme ýerine ýetirildi',
          'countProducts': 'Harytlar : ',
          'creatOrder': 'Sargyt döretmek',
          'date': 'Sene : ',
          'description': 'Düşündiriş',
          'discount': 'Arzanladyş',
          'download': 'Ýükle',
          'downloaded': 'Ýüklänlerim',
          'downloadFiles': 'Ýüklemek',
          'doYouWantToDeleteCart': 'Sebedi boşat !',
          'doYouWantToDeleteCartSubtitle': 'Siz hakykatdanam Sebedi boşatmakçymy ?',
          'emptyCart': 'Sebet boş',
          'error': 'Ýalňyşlyk ýüze çykdy täzeden synanşyň',
          'errorData': 'Girizeň maglumatyňyz ýalňyş !',
          'errorEmpty': 'Tekst gutusy boş bolup bilmez',
          'errorPassword': 'Parol azyndan 6 haryp bolmaly',
          'errorPassword2': 'Parolyňyz ýalňyş',
          'errorPhoneCount': 'Telefon belgiňiz 8 sanly bolmaly.',
          'errorTitle': 'Ýalňyş',
          'favorites': 'Halanlarym',
          'filter': 'Filter',
          'fixMachine': 'Bejeriş Hyzmaty',
          'giveLike': 'Bizi Play marketde bahalandyryň',
          'gramm': 'Gram',
          'hastags': 'Haştaglar',
          'home': 'Baş sahypa',
          'inOurHands': 'Şulary hem halap bilersiňiz',
          'kargoIncluded': 'Kargo mugt',
          'location': 'Haryt salgysy',
          'locations': 'Salgylarym',
          'log_out_title': 'Siz hakykatdanda ulgamdan çykmak isleýärsiňizmi ?',
          'log_out': 'Ulgamdan çyk',
          'login': 'Ulgama gir',
          'loginErrorFillBlanks': 'Boş ýerleri doldurmagyňyzy haýyş edýäris',
          'loginError': 'Ulgama giriň',
          'loginError1': 'Kimdir biri bu giriş maglumatlaryny ulanýar',
          'loginErrorSubtitle': 'Sargyt etmek üçin ulgama giriň',
          'loginErrorSubtitle1': 'Hyzmaty ýerine etmek üçin ulgama giriň',
          'material': 'Materialy',
          'maxPrice': 'Iň gymmat',
          'minPrice': 'Iň arzan',
          'minSumCount': 'Sargydyňyzyň jemi azyndan 50 manat bolmaly',
          'more': 'Goşmaçalar',
          'no': 'Ýok',
          'noConnection1': 'Aragatnaşyk ýok',
          'noConnection2': 'Internede baglanyp bolmady.Internet sazlamalaryňyzy barlap gaýtadan synanşyň !',
          'noConnection3': 'Täzeden synanş',
          'noData': 'Maglumat ýüklenmedi, täzeden synanşyň',
          'noData1': 'Wagtlaýynça maglumat ýok !',
          'noFile': 'Hiç hili Faýl ýok. Biz bilen habarlaşyň',
          'noHistoryOrders': 'Hiç hili sargyt etmediňiz',
          'noImage': 'Surat ýok',
          'noMoney': 'Pul ýok',
          'noMoneySubtitle': 'Hyzmaty ýerine ýetirmek üçin Puluňyz ýetenok',
          'noProductTitle': 'Gutardy',
          'note': 'Bellik',
          'notification': 'Bildirişler',
          'notWork': 'Işlänok',
          'notWorkSubtitle': 'Waglaýynça hyzmat işlänok',
          'order_status_come': 'Gelenler',
          'order_status_submission': 'Tabşyrylanlar',
          'order_status_wait': 'Sargyt edilenler',
          'order': 'Sargyt',
          'orders': 'Sargytlarym',
          'ordersDeleted': 'Salgylaryňyz pozuldy ',
          'orderSubtitle': 'Sargydyňyz ýerine ýetirmek üçin nobata goýuldy',
          'orderType': 'Sargyt görnüşi',
          'otp': 'Sms kod',
          'otpCheck': 'Otp Werfikasiýa',
          'otpErrorSubtitle': 'Sms koduňyzy ýene bir gezek barlaň',
          'otpErrorTitle': 'SMS kod ýalňyşlygy',
          'otpSubtitle': 'Telefon belgiňize gelen sms kody giriziň',
          'otpTitle': 'Ýazan belgiňize sms arkaly kod ugradylar.',
          'ourDeliveryService': 'Eltip bermek we töleg',
          'package': 'Gaplama',
          'paymentMethod': 'Töleg görnüşi',
          'phoneNumber': 'Telefon belgiňiz',
          'plain': 'Uçar',
          'price': 'Bahasy :',
          'priceProduct': 'Jemi Bahasy : ',
          'priceRange': 'Baha aralygy',
          'product': 'Haryt',
          'productAddToFav': 'Haryt halanlarym goşuldy',
          'productCount': 'Haryt sany',
          'productName': 'Haryt ady',
          'products': 'Harytlar',
          'profile': 'Ulanyjy',
          'quantity': 'Sany',
          'questions': 'Köp soralýan soraglar ?',
          'read': 'Oka',
          'referal_Code': 'Referal Kod',
          'referalDesc': 'Bu kod Üsti bilen ulanyjylary çagyryp bilersiňiz ve Pul gazanyp bilersiňiz',
          'referalKod': 'Referal kod',
          'referalKod1': 'Referal kodyňyz',
          'referalKodEarnedMoney': 'Jemi gazanç :',
          'referalKodUsedUser': 'Kody ulanan ulanyjylar',
          'search': 'Gözleg',
          'settings': 'Sazlamalar',
          'signInDialog': 'Ulgama girmek üçin ulanyjy maglumatlary doly we dogry şekilde dolduruň',
          'status': 'Ýagdaýy',
          'sum': 'Jemi',
          'uploadImage': 'Surat ýükle',
          'uploadImageProcessDone': 'Surat ýüklendi !',
          'userInfo': 'Ulanyjy maglumatlary :',
          'userName': 'Ulanyjy ady',
          'userpassword': 'Ulanyjy paroly',
          'versia': 'Wersiýa',
          'waiting': 'Garaşylýar',
          'waitMyMan': 'Garaşyň',
          'waitMyManSubtitle': 'Maglumat ýüklenýänça garaşyň',
          'yes': 'Hawwa',
        },
        'ru': {
          'yes': 'Да',
          'deleteTitle': 'Удалить',
          'deleteSubtitle': 'Вы действительно хотите удалить этот элемент?',
          'sosHistory': 'История SOS',
          'deviceList': 'Список устройствa',
          'select_language': 'Выберите язык',
          'selectMoreProducts': "Пожалуйста, выберите один или несколько продуктов",
          'done': "Выполнено",
          'cannotChangeOrderStatus': "Вы не можете изменить статус заказа",
          'notHigherThanSumPrice': "Цена со скидкой не может быть выше общей цены",
          "createOrder": "Создать заказ",
          'selectProducts': "Выбрать товары",
          'selectedProducts': 'Выбранные товары',
          'dateOrder': 'Дата заказа:',
          'sales': 'Заказы',
          'errorDontChangeData': "Вы ничего не изменили",
          'selectedImage': "Выбранное изображение",
          'totalProducts': "Все товары",
          'stockInHand': 'Запас в руке',
          'endOFProduct': 'Нет других продуктов',
          'noProduct': "Продукты не найдены",
          'aboutUs': 'О нас',
          'add': 'Double',
          'addAddress': 'Добавить адрес',
          'addCart': 'Добавить в корзину',
          'added': 'Добавлено',
          'addedSubtitle': 'Товар добавлен в корзину',
          'address': 'Домашний адрес',
          'agree': 'Подтвердите',
          'alreadyExist': "У нас нет ваших пользовательских данных. Пожалуйста, войдите в систему из раздела «Регистрация»",
          'appColor': 'Цвет приложения',
          'appColor1': 'Выберите цвет',
          'appColor2': 'Цвет 1',
          'appColor3': 'Цвет 2',
          'appColor4': 'Цвет 3',
          'appObtained': 'Если вы хотите открыть счет, пожалуйста, свяжитесь с человеком, который приобрел это приложение',
          'balance': 'Счет',
          'banner': 'Реклама',
          'brand': ' Бренд',
          'brandPP': ' Бренд',
          'brands': 'Бренды',
          'call': 'Звоните на',
          'callNumber': 'Номер телефона',
          'cartEmpty': 'Ваша корзина пуста',
          'cartEmptySubtitle': 'Вы ничего не добавили в корзину',
          'cash': 'Наличные',
          'cashSubtitle': 'Оплата наличными при оформлении заказа',
          'categoriesMini': 'Категории',
          'category': 'Категория',
          'changesUpdated': 'Данные изменены',
          'chooseTheColor': 'Выберите цвет: ',
          'chooseTheSize': 'Размер:',
          'clientAddress': 'Адрес пользователя',
          'clientNumber': 'Идентификатор',
          'clientNumber': 'Номер телефона',
          'come': 'Приходите',
          'contactInformation': 'Для связи: ',
          'copySuccess': 'Подтверждено',
          'copySuccesSubtitle': 'Copy Succeeded',
          'countProducts': 'Товары : ',
          'creatOrder': 'Создать заказ',
          'date': 'Вы: ',
          'description': 'Описание',
          'discount': 'Скидка',
          'download': 'Download',
          'doYouWantToDeleteCart': 'Пустая корзина!',
          'doYouWantToDeleteCartSubtitle': 'Вы уверены, что хотите удалить корзину?',
          'emptyCart': 'Корзина пуста',
          'error': 'Произошла ошибка, попробуйте еще раз',
          'errorData': 'Ваши входные данные неверны!',
          'errorEmpty': 'Текстовое поле не может быть пустым',
          'errorPassword': 'Пароль должен состоять не менее чем из 6 символов',
          'errorPassword2': 'Ваш пароль неверен',
          'errorPhoneCount': 'Ваш номер телефона должен состоять из 8 цифр',
          'errorTitle': 'Ошибка',
          'favorites': 'Мое избранное',
          'filter': 'Фильтр',
          'giveLike': 'Оцените нас на Play Market',
          'gram': 'Грамм',
          'hastags': 'Хэштеги',
          'home': 'Главная',
          'inOurHands': 'Вам также может понравиться это',
          'cargoIncluded': 'Груз бесплатный',
          'location': 'Адрес улицы',
          'locations': 'Места',
          'log_out_title': 'Вы уверены, что хотите выйти из системы?',
          'log_out': 'Выход',
          'login': 'Войти',
          'loginErrorFillBlanks': 'Пожалуйста, заполните пробелы',
          'loginError': 'Вход в систему',
          'loginError1': 'Кто-то использует этот логин',
          'loginErrorSubtitle': 'Войти для заказа',
          'loginErrorSubtitle1': 'Войти для выполнения услуги',
          'material': 'Материал',
          'maxPrice': 'Самый дорогой',
          'minPrice': 'Самый дешевый',
          'minSumCount': 'Ваш общий заказ должен быть не менее 50 манат',
          'more': 'Дополнения',
          'no': 'Нет',
          'noConnection1': 'Нет соединения',
          'noConnection2': "Не удалось подключиться к Интернету. Пожалуйста, проверьте настройки интернета и повторите попытку!",
          'noConnection3': 'Повторите попытку',
          'noData': 'Данные не загружены, попробуйте еще раз',
          'noData1': 'Временно нет данных!',
          'noFile': "Нет файла. Свяжитесь с нами",
          'noHistoryOrders': 'Вы не делали никаких заказов',
          'noImage': 'Нет изображения',
          'noMoney': 'Нет денег',
          'noMoneySubtitle': 'У вас недостаточно денег для выполнения услуги',
          'noProductTitle': 'Готово',
          'note': 'Примечание',
          'notification': 'Уведомления',
          'notWork': 'Не работает',
          'notWorkSubtitle': 'Служба предупреждений не работает',
          'order_status_come': 'Прибывает',
          'order_status_submission': 'Предоставлено',
          'order_status_wait': 'Заказано',
          'order': 'Заказ',
          'orders': 'Мои заказы',
          'ordersDeleted': 'Ваши заказы были удалены',
          'orderSubtitle': 'Ваш ордер был поставлен в очередь на исполнение',
          'orderType': 'Тип ордера',
          'otp': 'Sms-код',
          'otpCheck': 'Проверка Otp',
          'otpErrorSubtitle': 'Пожалуйста, проверьте ваш смс-код еще раз',
          'otpErrorTitle': 'Ошибка SMS-кода',
          'otpSubtitle': 'Введите SMS-код, полученный на ваш номер телефона',
          'otpTitle': 'На указанный вами номер был отправлен SMS-код',
          'ourDeliveryService': 'Доставка и оплата',
          'package': 'Пакет',
          'paymentMethod': 'Способ оплаты',
          'phoneNumber': 'Ваш номер телефона',
          'price': 'Цена:',
          'priceProduct': 'Общая цена: ',
          'priceRange': 'Диапазон цен',
          'product': 'Продукт',
          'productAddToFav': 'Добавлен в избранное',
          'productCount': 'Количество продуктов',
          'productName': 'Название продукта',
          'products': 'Продукты',
          'profile': 'Пользователь',
          'quantity': 'Количество',
          'questions': 'Часто задаваемые вопросы?',
          'read': 'Читать',
          'referral_Code': 'Код реферала',
          'referralDesc': 'Вы можете привлекать пользователей и зарабатывать деньги с помощью этого кода',
          'referralCode': 'Реферальный код',
          'referralKod1': 'Ваш реферальный код',
          'referralCodeEarnedMoney': 'Total Earning:',
          'referralKodUsedUser': 'referralKodUsedUser',
          'search': 'Поиск',
          'settings': 'Настройки',
          'signInDialog': 'Пожалуйста, заполните данные пользователя полностью и правильно, чтобы войти в устройство',
          'status': 'Статус',
          'sum': 'Всего',
          'uploadImage': 'Загрузить изображение',
          'uploadImageProcessDone': 'Изображение загружено!',
          'userInfo': 'Информация о пользователе:',
          'userName': 'Имя пользователя',
          'userpassword': 'Пароль пользователя',
          'versia': 'Версия',
          'waiting': 'Ожидание',
          'waitMyMan': 'Ожидание',
          'waitMyManSubtitle': 'Подождите, пока загрузится информация',
        },
        'en': {
          'yes': 'Yes',
          'deleteTitle': 'Delete',
          'deleteSubtitle': 'Are you sure you want to delete this item?',
          'sosHistory': 'SOS History',
          'deviceList': 'Device List',
          'select_language': 'Select a language',
          'selectMoreProducts': 'Please select one or more products',
          'done': "Done",
          'cannotChangeOrderStatus': "You cannot change the order status",
          "notHigherThanSumPrice": "Discount price cannot be higher than Total price",
          "createOrder": "Create Order",
          'selectProducts': 'Select Products',
          'selectedProducts': 'Selected Products',
          'dateOrder': 'Order Date:',
          'sales': "Orders",
          'errorDontChangeData': "You have not changed anything",
          'selectedImage': "Selected Image",
          'totalProducts': 'All Products',
          'stockInHand': 'Stock In Hand',
          'endOFProduct': 'No other products',
          'noProduct': "No products found",
          'aboutUs': 'About Us',
          'add': 'Double',
          'addAddress': 'Add Address',
          'addCart': 'Add to Cart',
          'added': 'Added',
          'addedSubtitle': 'Item added to cart',
          'address': 'Home Address',
          'agree': 'Confirm',
          'alreadyExist': "We don't have your user data. Please log in from the Register section",
          'appColor': 'App Color',
          'appColor1': 'Select Color',
          'appColor2': 'Color 1',
          'appColor3': 'Color 2',
          'appColor4': 'Color 3',
          'appObtained': 'If you would like to open an account, please contact the person who acquired this app',
          'balance': 'Account',
          'banner': 'Advertisement',
          'brand': 'Brand',
          'brandPP': 'Brand',
          'brands': 'Brands',
          'call': 'Call',
          'callNumber': 'Phone Number',
          'cart': 'Cart',
          'cartEmpty': 'Your cart is empty',
          'cartEmptySubtitle': 'You have not added anything to your cart.',
          'cash': 'Cash',
          'cashSubtitle': 'Payment in cash at checkout',
          'categoriesMini': 'Categories',
          'category': 'Category',
          'changesUpdated': 'Data changed',
          'chooseTheColor': 'Choose a color: ',
          'chooseTheSize': 'Size:',
          'clientAddress': 'User Address',
          'clientNumber': 'Identifier',
          'clientNumber': 'Phone Number',
          'come': 'Come',
          'contactInformation': 'To contact: ',
          'container': 'Container',
          'copySuccess': 'Confirmed',
          'copySuccesSubtitle': 'Copy Succeeded',
          'countProducts': 'Products: ',
          'creatOrder': 'Create Order',
          'date': 'You: ',
          'description': 'Description',
          'discount': 'Discount',
          'download': 'Download',
          'downloaded': 'Downloaded',
          'downloadFiles': 'Download',
          'doYouWantToDeleteCart': 'Empty Cart!',
          'doYouWantToDeleteCartSubtitle': 'Are you sure you want to delete the cart?',
          'emptyCart': 'Cart is empty',
          'error': 'An error occurred, please try again',
          'errorData': 'Your input data is incorrect!',
          'errorEmpty': 'Text box cannot be empty',
          'errorPassword': 'Password must be at least 6 characters long',
          'errorPassword2': 'Your password is incorrect',
          'errorPhoneCount': 'Your phone number must be 8 digits long.',
          'errorTitle': 'Error',
          'favorites': 'My favorites',
          'filter': 'Filter',
          'fixMachine': 'Maintenance Service',
          'giveLike': 'Rate us on Play Market',
          'gram': 'Gram',
          'hastags': 'Hashtags',
          'home': 'Home',
          'inOurHands': 'You may also like these',
          'cargoIncluded': 'Cargo is free',
          'location': 'Street Address',
          'locations': 'locations',
          'log_out_title': 'Are you sure you want to log out?',
          'log_out': 'Logout',
          'login': 'Log in',
          'loginErrorFillBlanks': 'Please fill in the blanks',
          'loginError': 'Log in',
          'loginError1': 'Someone is using this login',
          'loginErrorSubtitle': 'Login to order',
          'loginErrorSubtitle1': 'Login to perform service',
          'material': 'Material',
          'maxPrice': 'Most expensive',
          'minPrice': 'Cheapest',
          'minSumCount': 'Your total order must be at least 50 manats',
          'more': 'Additions',
          'no': 'No',
          'noConnection1': 'No connection',
          'noConnection2': 'Could not connect to the Internet. Please check your Internet settings and try again!',
          'noConnection3': 'Retry',
          'noData': 'Data not loaded, please try again',
          'noData1': 'Temporarily no data!',
          'noFile': 'No File. Contact Us',
          'noHistoryOrders': 'You have not made any orders',
          'noImage': 'No Image',
          'noMoney': 'No Money',
          'noMoneySubtitle': 'You do not have enough money to perform the service',
          'noProductTitle': 'Finished',
          'note': 'Note',
          'notification': 'Notifications',
          'notWork': 'Not working',
          'notWorkSubtitle': 'Warning service not working',
          'order_status_come': 'Arrives',
          'order_status_submission': 'Submitted',
          'order_status_wait': 'Ordered',
          'order': 'Order',
          'orders': 'My orders',
          'ordersDeleted': 'Your orders have been deleted',
          'orderSubtitle': 'Your order has been queued for execution',
          'orderType': 'Order Type',
          'otp': 'Sms Code',
          'otpCheck': 'Otp Verification',
          'otpErrorSubtitle': 'Please check your sms code again',
          'otpErrorTitle': 'SMS code error',
          'otpSubtitle': 'Enter the SMS code received on your phone number',
          'otpTitle': 'A code has been sent via SMS to the number you entered.',
          'ourDeliveryService': 'Delivery and payment',
          'package': 'Package',
          'paymentMethod': 'Payment Method',
          'phoneNumber': 'Your phone number',
          'plain': 'Flying',
          'price': 'Price:',
          'priceProduct': 'Total Price: ',
          'priceRange': 'Price Range',
          'product': 'Product',
          'productAddToFav': 'Added to my favorites',
          'productCount': 'Product Count',
          'productName': 'Product Name',
          'products': 'Maps',
          'profile': 'User',
          'quantity': 'Number',
          'questions': 'Frequently Asked Questions?',
          'read': 'Read',
          'referral_Code': 'Referral Code',
          'referralDesc': 'You can refer users and earn money with this code',
          'referralCode': 'Referral Code',
          'referralKod1': 'Your referral code',
          'referralCodeEarnedMoney': 'Total Earning:',
          'referralKodUsedUser': 'referralKodUsedUser',
          'search': 'Search',
          'settings': 'Settings',
          'signInDialog': 'Please fill in the user details completely and correctly to sign in to the device',
          'status': 'Status',
          'sum': 'Total',
          'uploadImage': 'Upload Image',
          'uploadImageProcessDone': 'Image uploaded!',
          'userInfo': 'User Info:',
          'userName': 'Username',
          'userpassword': 'User password',
          'versia': 'Version',
          'waiting': 'Waiting',
          'waitMyMan': 'Wait',
          'waitMyManSubtitle': 'Wait for information to load',
        },
      };
}
